version: '3.8'

# USED FOR DEVELOPMENT - Starts all the required services and configures them according to the 'dev.env' file
# The config ('dev.env') sets the same environment variables for every service for easier config of dev. environment

services:

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./dev.env

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    networks:
      - metrics-network
    volumes:
      - /var/lib/influxdb
    env_file:
      - ./dev.env

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - metrics-network
    volumes:
      - /var/lib/grafana
      - /etc/grafana/provisioning
    depends_on:
      - influxdb
    env_file:
      - ./dev.env

networks:
  metrics-network:
    driver: bridge