version: '3.8'

# Used to build and run the program in a Docker Container and starts all necessary services
# The config ('dev.env') sets the same environment variables for every service for easier config of dev. environment
# Run with: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml up --build

services:

  auth-app:
    build:
      context: .
      dockerfile: experimental.Dockerfile
    ports:
      - 8080:8080
    networks:
      - postgres-network
      - metrics-network
    environment:
      # Activates simulation in the application to produce metrics
      SPRING_PROFILES_ACTIVE: "dev, simulation"
    env_file:
      - ./dev.env
    depends_on:
      - postgres
      - influxdb

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    networks:
      - postgres-network
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./dev.env

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    networks:
      - metrics-network
    volumes:
      - /var/lib/influxdb
    env_file:
      - ./dev.env

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - metrics-network
    volumes:
      - /var/lib/grafana
      - /etc/grafana/provisioning
    depends_on:
      - influxdb
    env_file:
      - ./dev.env

networks:
  postgres-network:
    driver: bridge
  metrics-network:
    driver: bridge