spring:
  datasource:
    # Using PostgreSQL for development
    url: jdbc:postgresql://${AUTH_DB_URL:localhost}:${AUTH_DB_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:""}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop

management:
  metrics:
    export:
      influx:
        # Enable InfluxDB while 'dev' profile is active
        enabled: true
        step: 5s
        uri: ${INFLUXDB_URI:http://localhost:8086}
        db: ${INFLUXDB_DB:metrics}
        user-name: ${INFLUXDB_USER:user}
        password: ${INFLUXDB_USER_PASSWORD:user}
