#!/bin/bash
set -e

docker --version
# Extract layers from the layered Spring Boot application
java -Djarmode=layertools -jar ./target/$PROJECT_NAME*.jar extract
# Sign in to Docker
echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
# Build the Docker Image
docker build -f travis.Dockerfile -t "$PROJECT_NAME" .