#!/bin/bash
set -e
# Full image name with registry
export IMAGE_NAME="$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$PROJECT_NAME"

echo "Building and pushing the Docker Image to the repository"

# Build image
echo "Building Docker Image - this might take a while..."
docker build -f Dockerfile -t tmp .

# Tag images
echo "Tagging the image"
docker tag tmp "$IMAGE_NAME":latest
docker tag tmp "$IMAGE_NAME":"$TRAVIS_COMMIT"

# Push the tagged images
echo "Pushing the image to registry"
docker push "$IMAGE_NAME"
#docker push "$IMAGE_NAME" | bash &>/dev/null

echo "Built and pushed image with tag '$TRAVIS_COMMIT' and 'latest' to the repository"
