#!/bin/bash
set -e

# Updates Docker on Travis CI from 18.0.6 to the current stable release (19.03.13 as of 17.11.2020)
echo "Updating Docker"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
docker --version
echo "Done updating Docker"