{
 "title": "Beer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Keg Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Beercentage (% of keg capacity filled)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "beer_kegs_avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Keg refilling time",
   "type": "graph",
   "description": "Displays the time spent refilling kegs. ",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Refill time" }
   ],
   "targets": [
    {
     "measurement": "beer_kegs_fill_single",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current refill run timer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "beer_kegs_fill_all",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Sipping Status",
   "type": "stat",
   "description": "Shows the results of incoming attempts to take a sip from a mug.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "beer_sips_count",
     "query": "SELECT sum(\"value\") FROM \"beer_sips_count\" WHERE $timeFilter GROUP BY \"result\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Amount tapped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "beer_taps_volume",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean amount tapped",
   "type": "graph",
   "description": "Viser snittetstørrelse av muggepåfyllinger",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dL" } },
   "yaxes": [
    { "format": "dL" }
   ],
   "targets": [
    {
     "measurement": "beer_taps_volume",
     "query": "SELECT \"mean\" FROM \"beer_tap_volume\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}